# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P3_Par_Impar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(415, 243)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_checar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_checar.setGeometry(QtCore.QRect(60, 100, 81, 31))
        self.btn_checar.setObjectName("btn_checar")
        self.btn_limpiar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_limpiar.setGeometry(QtCore.QRect(180, 100, 81, 31))
        self.btn_limpiar.setObjectName("btn_limpiar")
        self.txt_n = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_n.setGeometry(QtCore.QRect(100, 50, 141, 31))
        self.txt_n.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_n.setObjectName("txt_n")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 20, 111, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 415, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_checar.setText(_translate("MainWindow", "Checar"))
        self.btn_limpiar.setText(_translate("MainWindow", "Limpiar"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Ingrese un numero:</p></body></html>"))
