# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ejercicios.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(539, 423)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 30, 111, 31))
        self.label.setObjectName("label")
        self.btn_ejercicio8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ejercicio8.setGeometry(QtCore.QRect(290, 260, 121, 41))
        self.btn_ejercicio8.setObjectName("btn_ejercicio8")
        self.btn_ejercicio9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ejercicio9.setGeometry(QtCore.QRect(130, 320, 121, 41))
        self.btn_ejercicio9.setObjectName("btn_ejercicio9")
        self.btn_ejercicio1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ejercicio1.setGeometry(QtCore.QRect(130, 80, 121, 41))
        self.btn_ejercicio1.setObjectName("btn_ejercicio1")
        self.btn_ejercicio2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ejercicio2.setGeometry(QtCore.QRect(290, 80, 121, 41))
        self.btn_ejercicio2.setObjectName("btn_ejercicio2")
        self.btn_ejercicio3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ejercicio3.setGeometry(QtCore.QRect(130, 140, 121, 41))
        self.btn_ejercicio3.setObjectName("btn_ejercicio3")
        self.btn_ejercicio4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ejercicio4.setGeometry(QtCore.QRect(290, 140, 121, 41))
        self.btn_ejercicio4.setObjectName("btn_ejercicio4")
        self.btn_ejercicio5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ejercicio5.setGeometry(QtCore.QRect(130, 200, 121, 41))
        self.btn_ejercicio5.setObjectName("btn_ejercicio5")
        self.btn_ejercicio6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ejercicio6.setGeometry(QtCore.QRect(290, 200, 121, 41))
        self.btn_ejercicio6.setObjectName("btn_ejercicio6")
        self.btn_ejercicio7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ejercicio7.setGeometry(QtCore.QRect(130, 260, 121, 41))
        self.btn_ejercicio7.setObjectName("btn_ejercicio7")
        self.btn_ejercicio10 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ejercicio10.setGeometry(QtCore.QRect(290, 320, 121, 41))
        self.btn_ejercicio10.setObjectName("btn_ejercicio10")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, 10, 141, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/logos/Imagenes/logo fit.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(460, 330, 61, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/logos/Imagenes/logoCT.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 141, 61))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/logos/Imagenes/logo uat.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Ejercicios</span></p></body></html>"))
        self.btn_ejercicio8.setText(_translate("MainWindow", "Ejercicio 8"))
        self.btn_ejercicio9.setText(_translate("MainWindow", "Ejercicio 9"))
        self.btn_ejercicio1.setText(_translate("MainWindow", "Ejercicio 1"))
        self.btn_ejercicio2.setText(_translate("MainWindow", "Ejercicio 2"))
        self.btn_ejercicio3.setText(_translate("MainWindow", "Ejercicio 3"))
        self.btn_ejercicio4.setText(_translate("MainWindow", "Ejercicio 4"))
        self.btn_ejercicio5.setText(_translate("MainWindow", "Ejercicio 5"))
        self.btn_ejercicio6.setText(_translate("MainWindow", "Ejercicio 6"))
        self.btn_ejercicio7.setText(_translate("MainWindow", "Ejercicio 7"))
        self.btn_ejercicio10.setText(_translate("MainWindow", "Ejercicio 10"))
import recursos_rc
