# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E9_ViajeDeEstudios.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(373, 330)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 20, 131, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 80, 81, 21))
        self.label_2.setObjectName("label_2")
        self.txt_asistentes = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_asistentes.setGeometry(QtCore.QRect(170, 80, 113, 20))
        self.txt_asistentes.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_asistentes.setObjectName("txt_asistentes")
        self.txt_cobrar = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_cobrar.setGeometry(QtCore.QRect(40, 210, 113, 20))
        self.txt_cobrar.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_cobrar.setObjectName("txt_cobrar")
        self.btn_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calcular.setGeometry(QtCore.QRect(80, 130, 221, 31))
        self.btn_calcular.setObjectName("btn_calcular")
        self.txt_pagar = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_pagar.setGeometry(QtCore.QRect(200, 210, 113, 20))
        self.txt_pagar.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_pagar.setObjectName("txt_pagar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 190, 91, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 190, 151, 20))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 373, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Viaje de estudios</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">N° de asistentes:</p></body></html>"))
        self.btn_calcular.setText(_translate("MainWindow", "Calcular"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Debe de cobrar:</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Debe de pagar por el servicio:</p></body></html>"))
